version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes: 
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
